### ISSUE TITLE
builidng error

### ISSUE THREAD

**Issue by alirezarabiei7239** [linyicheng1/LET-NET#10]
Hi and thanks for your work
for building this commant got error cmake .. && make -j4 cuase there is no cmkaelist out of this project folder
i cope and paste it in upper folder now I am getting this error 

`-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) 
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) 
-- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND) 
-- Configuring done (0.2s)
CMake Error at /opt/homebrew/lib/cmake/ncnn/ncnn.cmake:61 (set_target_properties):
  The link interface of target "ncnn" contains:

    OpenMP::OpenMP_CXX

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  /opt/homebrew/lib/cmake/ncnn/ncnnConfig.cmake:42 (include)
  CMakeLists.txt:11 (find_package)
`

can you please help me?

**Comment by linyicheng1** [comment]
You can try installing the OpenMP library.

**Comment by alirezarabiei7239** [comment]
thanks for your reply

but when I try to build ncnn
i got this error 


make[2]: *** No rule to make target `../vulkansdk-macos-1.2.189.0/MoltenVK/dylib/macOS/libMoltenVK.dylib', needed by `benchmark/benchncnn'.  Stop.
make[1]: *** [benchmark/CMakeFiles/benchncnn.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** No rule to make target `../vulkansdk-macos-1.2.189.0/MoltenVK/dylib/macOS/libMoltenVK.dylib', needed by `examples/fasterrcnn'.  Stop.
make[1]: *** [examples/CMakeFiles/fasterrcnn.dir/all] Error 2
make[2]: *** No rule to make target `../vulkansdk-macos-1.2.189.0/MoltenVK/dylib/macOS/libMoltenVK.dylib', needed by `examples/squeezenet_c_api'.  Stop.
make[2]: *** No rule to make target `../vulkansdk-macos-1.2.189.0/MoltenVK/dylib/macOS/libMoltenVK.dylib', needed by `examples/squeezenet'.  Stop.
make[1]: *** [examples/CMakeFiles/squeezenet.dir/all] Error 2
make[1]: *** [examples/CMakeFiles/squeezenet_c_api.dir/all] Error 2
make: *** [all] Error 2
[  0%] Built target GenericCodeGen
[  0%] Built target OGLCompiler
[  0%] Built target OSDependent
[  4%] Built target MachineIndependent
[  5%] Built target glslang
[  5%] Built target glslang-default-resource-limits
[  7%] Built target SPIRV
[ 62%] Built target ncnn-generate-spirv
[ 92%] Built target ncnn
make[2]: *** No rule to make target `../vulkansdk-macos-1.2.189.0/MoltenVK/dylib/macOS/libMoltenVK.dylib', needed by `benchmark/benchncnn'.  Stop.
make[1]: *** [benchmark/CMakeFiles/benchncnn.dir/all] Error 2
make: *** [all] Error 2

can you please help me
