### ISSUE TITLE
files needed for train.py

### ISSUE THREAD

**Issue by pedrozarin2024** [linyicheng1/LET-NET#16]
could you please add files like /media/server/4cda377d-28db-4424-921c-6a1e0545ceeb/linyicheng/py_project/ALIKE_code/training/log_train/train/Version-0708-221706/checkpoints/epoch=79-mean_metric=0.4917.ckpt that used in the train.py file ?
or how to by pass it ?

**Comment by linyicheng1** [comment]
This file is only used for testing and not for training
