### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by kourner** [linyicheng1/LET-NET#17]
Amazing work, thank you for making it open source. 

I'd like to further research based on your work. however, https://datasets.epfl.ch/disk-data/ is closed, and I can't download the necessary data for model training. Could you share Megadeth and iwm2020-val dataset? 

Thank you very much, best wishes!

**Comment by linyicheng1** [comment]
I use this file download the dataset

#/usr/bin/env bash

# get the data (zipped)
wget -r https://datasets.epfl.ch/disk-data/index.html

cd datasets.epfl.ch/disk-data;

# check for MD5 match
md5sum -c md5sum.txt;
if [ $? ]; then
    echo "MD5 mismatch (corrupt download)";
    return 1;
fi

# create a crude progress counter
ITER=1;
TOTAL=138;
# unzip test scenes
cd imw2020-val/scenes;
for SCENE_TAR in *.tar.gz; do
    echo "Unzipping $SCENE_TAR ($ITER / $TOTAL)";
    tar -xz --strip-components=3 -f $SCENE_TAR;
    rm $SCENE_TAR;
    ITER=$(($ITER+1));
done

# unzip megadepth scenes
cd ../../megadepth/scenes;
for SCENE_TAR in *.tar; do
    echo "Unzipping $SCENE_TAR ($ITER / $TOTAL)";
    tar -x --strip-components=3 -f $SCENE_TAR;
    rm $SCENE_TAR;
    ITER=$(($ITER+1));
done

# create symlinks as train and test datasets
cd ../../
ln -s megadepth train
ln -s imw2020-val test

**Comment by kourner** [comment]
Thank you for your response. I've tried using the script, but the website https://datasets.epfl.ch/disk-data/ is down, and I can't download the dataset anymore. If it's not too much trouble, could you upload the disk-data dataset to Google Drive or Baidu Netdisk? I guess many others are also in need of this dataset. Thank you again.

**Comment by kourner** [comment]
Excellent work, I would like to conduct further research based on this work. However, the official website for the megadepth disk dataset has been shut down, making it impossible to download. Could anyone share the megadepth disk dataset? I am willing to pay for it.

**Comment by linyicheng1** [comment]
The dataset will be uploaded to Baidu Netdisk, under the copyright of the original author.

**Comment by kourner** [comment]
> The dataset will be uploaded to Baidu Netdisk, under the copyright of the original author.

Thanks a million!

**Comment by linyicheng1** [comment]
The training dataset is uploaded to https://pan.baidu.com/s/1D61PeZ6tQovehvyawGUpcA，ypnw
