### ISSUE TITLE
files needed for train_wrapper.py

### ISSUE THREAD

**Issue by kourner** [linyicheng1/LET-NET#19]
File "/home/code/LETNet/LETNet/training/../training/train_wrapper.py", line 134, in __init__
    self.errors = load_precompute_errors(str(Path(__file__).parent / 'errors.pkl'))
                  ^^^^^^^^^^^^^^^^^^^^^^

I cannot find the errors.pkl in the repo. Could you provide the errors.pkl or how to generate it?

**Comment by kourner** [comment]
I found it.

**Comment by zhixuan4123** [comment]
> I found it.

I have the same issue as you. How did you handle it? Thank you.

**Comment by kourner** [comment]
> > I found it.
> 
> I have the same issue as you. How did you handle it? Thank you.

Can be found here: https://github.com/Shiaoming/ALIKE/blob/main/assets/ALIKE_code.zip

**Comment by zhixuan4123** [comment]
> > > I found it.
> > 
> > 
> > I have the same issue as you. How did you handle it? Thank you.
> 
> Can be found here: https://github.com/Shiaoming/ALIKE/blob/main/assets/ALIKE_code.zip

Thank you for your help！
