### ISSUE TITLE
Pls has anyone run the grayscale image of the euroc dataset played by rosbag？

### ISSUE THREAD

**Issue by zwq-slamer** [linyicheng1/LET-NET#27]

**Comment by deepConnectionism** [comment]
can run

**Comment by zwq-slamer** [comment]
> can run

#13 Thank you very much for the proposal. 
I am now running into some problems that should be the number of image channels, about openCV error, can you share the code you modified? Thank you very much for your help

**Comment by deepConnectionism** [comment]
@zwq-slamer  https://github.com/linyicheng1/LET-NET/issues/18#issuecomment-2235224171

**Comment by zwq-slamer** [comment]
> @zwq-slamer [#18 (comment)](https://github.com/linyicheng1/LET-NET/issues/18#issuecomment-2235224171)

感谢！我注意到了您提供的修改方案，我已作了修改，但是好像并不work，
我运行了`roslaunch vins_estimator euroc.launch ` 以及 播放了euroc的MH01.bag包
```
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.2.0) ../modules/imgproc/src/color.simd_helpers.hpp:92: error: (-2:Unspecified error) in function 'cv::impl::{anonymous}::CvtHelper<VScn, VDcn, VDepth, sizePolicy>::CvtHelper(cv::InputArray, cv::OutputArray, int) [with VScn = cv::impl::{anonymous}::Set<3, 4>; VDcn = cv::impl::{anonymous}::Set<1>; VDepth = cv::impl::{anonymous}::Set<0, 2, 5>; cv::impl::{anonymous}::SizePolicy sizePolicy = cv::impl::<unnamed>::NONE; cv::InputArray = const cv::_InputArray&; cv::OutputArray = const cv::_OutputArray&]'
> Invalid number of channels in input image:
>     'VScn::contains(scn)'
> where
>     'scn' is 1

[feature_tracker-1] process has died [pid 61273, exit code -6, cmd /home/zwq/LET-NET/assets/vins_mono/devel/lib/feature_tracker/feature_tracker __name:=feature_tracker __log:=/home/zwq/.ros/log/2fb5f034-7175-11ef-8096-55fc09344e93/feature_tracker-1.log].
log file: /home/zwq/.ros/log/2fb5f034-7175-11ef-8096-55fc09344e93/feature_tracker-1*.log
```
看起来应该就是图像通道数的问题，在源代码其他部分您是否还做了其他修改以适应灰度图的输入

**Comment by deepConnectionism** [comment]
@zwq-slamer You specify the COLOR space conversion code as COLOR. This means that your input should be in RGB format and your output should be in gray format.

The problem is that you create the  input as a `CV_8UC1`) . You can solve the problem by creating it as a `CV_8UC3` .
