### ISSUE TITLE
train

### ISSUE THREAD

**Issue by TianfaYao** [linyicheng1/LET-NET#5]
The work is very good, can you list the references, or the open source **training** code and model structure?

**Comment by linyicheng1** [comment]
All training code and related papers will be made public when the paper is accepted, and subsequent work is completed.

**Comment by l-sf** [comment]
Thank you for your great work! May I ask if the ONNX format model can be provided? My project runs on Jetson and I need ONNX model to convert to Tensorrt engine.

**Comment by linyicheng1** [comment]
The training code is released
