### ISSUE TITLE
About Generalization

### ISSUE THREAD

**Issue by qiaozhijian** [linyicheng1/LET-NET#6]
Nice work! Have you tested it on the public dataset? Will it outperform the original VINS-Mono in the most sequences reported in the paper?

**Comment by linyicheng1** [comment]
In all sequences tested so far, especially in scenes with large light variations the performance is due to the original VINS-Mono. but the current test is not very comprehensive, which is our follow-up work. The method has also shown its advantages in the ICCV2023 SLAM challenge.

**Comment by qiaozhijian** [comment]
Thanks for reply. look forward to your further achievements！
